-- CREATE TABLE profiles(
--   id VARCHAR(255) NOT NULL,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL, 
--   picture VARCHAR(255) NOT NULL,
--   PRIMARY KEY (id)
-- )
--  CREATE TABLE products(
--   id INT NOT NULL AUTO_INCREMENT,
--   name VARCHAR(255) NOT NULL,
--   isAvailable TINYINT NOT NULL, 
--   picture VARCHAR(255) NOT NULL,
--   creatorId VARCHAR(255) NOT NULL,
--   PRIMARY KEY (id),
--   FOREIGN KEY (creatorId)
--     REFERENCES profiles(id)
--     ON DELETE CASCADE
-- )
-- ALTER TABLE products
-- ADD description VARCHAR(255) NOT NULL